export const CONST_REQUEST_STATUS_ENUM = {
  PENDING: "PENDING",
  TOPAY: "TOPAY",
  PROCESSING: "PROCESSING",
  TOCOMPLETE: "TOCOMPLETE",
  CLOSED: "CLOSED",
};

export const CONST_REQUEST_STATUS = [
  "PENDING",
  "TOPAY",
  "PROCESSING",
  "TOCOMPLETE",
  "CLOSED",
];

export const REQUEST_ERROR_NOT_FOUND = "Request type not found!";
